# GET  https://103.12.1.103/PayRollRevampAPI/Payroll/GetStaffOverTimeDetailsUpload  HTTP/1.1


# GET  https://103.12.1.103/PayRollRevampAPI/Payroll/GetStaffByEmployeeID?EmployeID=9999 HTTP/1.1
# GET  https://103.12.1.103/PayRollRevampAPI/HR/GetAttendance HTTP/1.1

# {
#           'StaffID': this.StaffID,
#           'OT_name': this.exceldata[this.i].name,
#           'Hours': this.exceldata[this.i].hours,
#           'PayDate': this.Date
# }
# POST https://103.12.1.103/PayRollRevampAPI/HR/UpdateAttendanceWeb HTTP/1.1

# Content-Type: "application/json"

# GET https://103.12.1.103/PayRollRevampAPI/Employee/GetStaffLeaves?ID=38243&TypeID=1&Sdate=2023-05-19&Edate=2023-05-19

# GET https://103.12.1.103/PayRollRevampAPI/HR/GetAttendanceByManagerID?Supervisor=20540&SDate=2023-05-19&EDate=2023-05-22  HTTP/1.1
GET https://103.12.1.103/PayRollRevampAPI/Payroll/GetStaffByEmployeID?ID=38244 HTTP/1.1